version: "3"

services:
  postgres:
    container_name: budget-db
    image: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: thisisasecurepassword
      POSTGRES_USER: budget_user
      POSTGRES_DB: budget_dev
    volumes:
      - ./db/postgres_data:/var/lib/postgres
    networks:
      - budget
  
  budget-api:
    container_name: budget-api
    build: .
    volumes:
      - type: bind
        source: ./config
        target: /usr/local/app/config/
    depends_on: 
      - postgres
    ports:
      - 5000:5000
    networks:
      - budget

networks:
  budget:
    driver: bridge