version: "3"

services:
  postgres:
    container_name: budget-db
    image: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: thisisasecurepassword
      POSTGRES_USER: budget_user
      POSTGRES_DB: budget_dev
    volumes:
      - ./db/postgres_data:/var/lib/postgres
    networks:
      - budget
  
  budget-api:
    container_name: budget-api
    build: .
    volumes:
      - type: bind
        source: ./config
        target: /usr/local/app/config/
    depends_on: 
      - postgres
    ports:
      - 5000:5000
    networks:
      - budget

  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - 4566-4599:4566-4599
      - 8081:8081
    environment:
      - SERVICES=kinesis,s3,sqs
      - DEFAULT_REGION=us-east-1
      - PORT_WEB_UI=9000
      - START_WEB=1
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    networks:
      - budget
    volumes:
      - /tmp/localstack:/tmp/localstack
      - /tmp/localstack/run/docker.sock:/var/run/docker.sock

networks:
  budget:
    driver: bridge