"""Add Budget amount

Revision ID: 3c4b540d4c13
Revises: 2122b2dd09fd
Create Date: 2020-11-18 14:30:17.681285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c4b540d4c13'
down_revision = '2122b2dd09fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budget_items', sa.Column('amount', sa.Integer(), nullable=True))
    op.add_column('budgets', sa.Column('amount', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('budgets', 'amount')
    op.drop_column('budget_items', 'amount')
    # ### end Alembic commands ###
