"""Add relation from budgets to users

Revision ID: 41c70cfb0ddf
Revises: 3c4b540d4c13
Create Date: 2020-11-22 14:38:29.978177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41c70cfb0ddf'
down_revision = '3c4b540d4c13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('budgets_created_by_fkey', 'budgets', type_='foreignkey')
    op.create_foreign_key(None, 'budgets', 'users', ['created_by'], ['id'])
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_constraint(None, 'budgets', type_='foreignkey')
    op.create_foreign_key('budgets_created_by_fkey', 'budgets', 'users', ['created_by'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
