"""Change Budget type to category

Revision ID: 6acca9192dda
Revises: d656427b061e
Create Date: 2020-11-18 13:17:57.710547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6acca9192dda'
down_revision = 'd656427b061e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budgets', sa.Column('category', sa.String(length=50), nullable=True))
    op.drop_column('budgets', 'type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budgets', sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('budgets', 'category')
    # ### end Alembic commands ###
